### PR TITLE
feature: Add decimal coverage for files CY-6221

### PR DESCRIPTION
**Pull request by prcr**
Updates the screenshots that display coverage on the **Files**, **Commits**, and **Pull requests** pages.

### :eyes: Live preview
- https://feature-decimal-coverage-files-cy-6--docs-codacy.netlify.app/repositories/files/
- https://feature-decimal-coverage-files-cy-6--docs-codacy.netlify.app/repositories/commits/#files-tab
- https://feature-decimal-coverage-files-cy-6--docs-codacy.netlify.app/repositories/pull-requests/#files-tab

### :construction: To do
- [x] Wait until [CY-6208](https://codacy.atlassian.net/browse/CY-6208) is released

### CODE REVIEW

**Comment by vascorsd** [comment]
Does the diff coverage have decimals currently? I think we are only supposed to be changing the screenshots to have the coverage variation with decimals.

**Comment by fjrdomingues** [comment]
Hey @prcr you are living in the future man 😄 
The [CY-6208](https://codacy.atlassian.net/browse/CY-6208) will start showing decimals on the Files page only. The commits/PRs pages and Gates will be done in the next sprints.

**Review by inesgomas — APPROVED** [review]

**Review by rubencodacy — COMMENTED** [review]
We did not make the change to show decimals on the diff coverage, this epic takes only into account coverage variation for files.

**Comment by prcr** [comment]
I was unsure about exactly which pages and values would be updated at which time, so I decided to include all the updates in this pull request so that later on we could easily decide when and what to publish. Sorry if I caused you some confusion, I should probably have marked this pull request as Draft.

I'll wait until the changes are in production before I publish the corresponding doc updates. :+1:

**Comment by prcr** [comment]
This pull request now includes only the changes that will be released on [CY-6208](https://codacy.atlassian.net/browse/CY-6208).

**Review by inesgomas — APPROVED** [review]

**Pull request merged**
