### PR TITLE
feature: Update permissions of GitLab Maintainter role CY-5882

### PR DESCRIPTION
**Pull request by prcr**
Updates the page "Roles and permissions for synced organizations" to reflect the changes from [CY-5876](https://codacy.atlassian.net/browse/CY-5876).

See also https://github.com/codacy/docs/pull/1130.

### :eyes: Live preview
https://deploy-preview-1113--docs-codacy.netlify.app/organizations/roles-and-permissions-for-synced-organizations/

### :construction: To do
- [x] Clean up styles used to highlight changes
- [x] Wait for [CY-5876](https://codacy.atlassian.net/browse/CY-5876) to be released

### CODE REVIEW

**Comment by prcr** [comment]
I updated the Maintainer role permissions for the operations "Ignore issues and files, configure code patterns, [...]" to reflect the most up-to-date Engineering solution.

**Comment by mrfyda** [comment]
hello 👋 

first of all, the changes related to CY-5882 look good!
and nice way to visualize the changes 💪 

still, I wanted to share some thoughts:

1. these changes are a step in the right direction, and since there doesn't seem to be a reason not to do the same changes for GitHub, I've opened a topic on ProductBoard to track this and prioritize it: https://codacy.productboard.com/feature-board/4088239-vms-all-themes/features/12624918/detail
1. I found some suspicious permission values that I believe are wrong (see the attachment, red for things I confirmed, orange for things I haven't confirmed)
    1. GitHub | Repository Write | Configure Repository → should be No
    1. GitHub | Repository Maintain | Configure Repository → should be No
    1. Bitbucket | Write | Upload coverage → expect it to be Yes (?)

cc @terciosoares 

screencapture-deploy-preview-1113-docs-codacy-netlify-app-organizations-roles-and-permissions-for-synced-organizations-2022-03-24-11_39_20

**Comment by terciosoares** [comment]
Hi. Thank you for the additional information @mrfyda.

**Comment by prcr** [comment]
> 2\. I found some suspicious permission values that I believe are wrong

I opened a separate pull request to handle the fixes for this: https://github.com/codacy/docs/pull/1129

**Comment by prcr** [comment]
> Not sure if this would be the PR to include this, but do we want to add a Remove repository column? or change the Add to Add/Remove since the values will be the same smile

This applies to all Git providers, am I correct? If so :pray:, I would prefer making that improvement on a separate pull request, just to help clarify that it isn't related to the change we're making to the GitLab Maintainer role.

Would you like to have a go at it @lventura-codacy? :rocket:

**Pull request merged**
