### PR TITLE
correct significant omission in OSS tool list

### PR DESCRIPTION
**Pull request by ganncamp**
-   Why are these changes required? What problem do them solve?
The Special Thanks page omits mention of one of the OSS tools used: Sonar C#, as mentioned here: https://docs.codacy.com/getting-started/supported-languages-and-tools/

### CODE REVIEW

**Comment by ganncamp** [comment]
Live preview: https://github.com/codacy/docs/blob/3ec8a1e43793ead3ea8344b4e9abc19953ea66b6/docs/special-thanks.md

**Comment by prcr** [comment]
Hello @ganncamp and thank you for contributing to updating the Codacy docs!

Unfortunately, we haven't been doing a great job in keeping the "Special thanks" page updated. We'll make sure to give a higher priority to an internal ticket that we already have to do a full review of this page and ensure that all tools are mentioned. :+1: 

We usually link each tool to its corresponding OSS repository, which in this case would be <https://github.com/SonarSource/sonar-dotnet>. Could you please make this change before I approve your pull request?

**Comment by ganncamp** [comment]
Thanks @prcr! I've updated the links. It wasn't the case for Pylint, so I thought there was a choice.

**Review by prcr — APPROVED** [review]

**Comment by prcr** [comment]
> Thanks @prcr! I've updated the links. It wasn't the case for Pylint, so I thought there was a choice.

Thanks for the quick reply @ganncamp, I'm merging the changes now!

Regarding Pylint, we'll definitely want to make things more consistent when we review this page.

**Pull request merged**
