### PR TITLE
Update obtaining-current-issues-in-repositories.md

### PR DESCRIPTION
**Pull request by sampadap03**
Updates cURL command for fetching issues. It is more user-readable.
Reference to: https://app.codacy.com/api/api-docs?_ga=2.157222907.1708164755.1651837780-813421981.1651215780#searchrepositoryissues

### :eyes: Live preview
[https://docs.codacy.com/codacy-api/examples/obtaining-current-issues-in-repositories/](https://docs.codacy.com/codacy-api/examples/obtaining-current-issues-in-repositories/)

### :construction: To do
-   [ ] If relevant, include the Jira issue key at the end of the pull request title
-   [ ] Perform a self-review of the changes
-   [ ] Fix any issues reported by the CI/CD

### CODE REVIEW

**Comment by prcr** [comment]
Hello @sampadap03, and thank you for your suggestion!

Our idea on these API documentation pages was to show how calling the API endpoints against specific repositories/organizations/Git providers would look like. So that is why we opted to include the explicit values instead of the placeholders that are available on the [endpoint reference](https://app.codacy.com/api/api-docs#searchrepositoryissues).

Does this make sense to you, or do you still think that it would be more useful to you if we just included the placeholders in the examples?

**Comment by prcr** [comment]
Hi again @sampadap03,

I liked your suggestion to make clear "which blanks need to be filled". I opened https://github.com/codacy/docs/pull/1251 to apply this consistently across all our current examples, what do you think?

**Comment by prcr** [comment]
In the meantime, I've already merged #1251 and I'm going to close this pull request now, but do let me know if you have any further feedback @sampadap03. :+1: 

Thank you for your contribution to the Codacy docs!

**Comment by sampadap03** [comment]
Hey @prcr, thanks for considering! Glad you like it :) Sorry for replying late, this PR got skipped from my mind. #1251 looks good, keep up the good work! 👍

**Pull request closed without merging**
