### PR TITLE
feat: Improve coverage troubleshooting DOCS-504 DOCS-496

### LINKED ISSUE #1549: [DOCS-496] Clarify which commits must have coverage data to calculate each coverage metric
**Type of feedback**

-   [ ] Bug or incorrect information
-   [ ] Missing information
-   [ ] Outdated information
-   [X] Enhancement
-   [ ] Other

**Feedback**

We should explicitly describe which commits must have coverage data so that Codacy can calculate:

* **Coverage variation**: both the **head commit** of the pull request branch and **common ancestor commit** must have coverage data
* **Diff coverage**: only the **head commit** of the pull request branch needs to have coverage data

Here's another way of explaining the associated logic:

```
A: Ancestor commit
H: Head commit

A & H =>  Codacy calculates the coverage variation and the diff coverage
!A & H => Codacy calculates diff coverage only (error on coverage variation)
A & !H => Codacy can't calculate any coverage metric (error on both coverage metrics)
!A & !H => Codacy can't calculate any coverage metric (error on both coverage metrics)
```

**Affected pages**
This feedback applies to the following documentation pages / URLs:

https://docs.codacy.com/coverage-reporter/#validating-coverage

**Additional context**
If applicable, provide any other context or information that could be useful in updating the documentation:

- This feedback was provided by @fjrdomingues after the [insights from this Jira issue](https://codacy.atlassian.net/browse/COV-14?focusedCommentId=53036).
- See also [this private Slack message](https://codacy.slack.com/archives/DT36W0290/p1671037890572599)

### PR DESCRIPTION
**Pull request by prcr**
Improves the coverage setup troubleshooting by:

- Stressing that the CI/CD must upload coverage data for **all commits pushed to the repository** and include coverage data for **all tested files in the repository**

    image

- Clarifying the relevant pull request commits **required to calculate each coverage metric**

    image

- Mentioning two alternatives for **checking if pull requests are missing coverage data** for either the common ancestor or head commits

    image

Fixes #1549.

### :eyes: Live preview
https://feat-coverage-link-api-example-docs--docs-codacy.netlify.app/coverage-reporter/

### CODE REVIEW

**Comment by prcr** [comment]
@nadiia-balaian I'm tagging you just to check if you're OK with having your user name show up on a [screenshot for the docs](https://github.com/codacy/docs/pull/1605/files#diff-f0e99e4e35525fb54c5e04b5149ab27311028974f2ea3534f1438b65d2283d6f).

**Comment by mrfyda** [comment]
> Stressing that the CI/CD must upload coverage data for all commits pushed to the repository
@prcr I'm not sure if we are also stressing that users must send coverage information for all files for every commit, regardless if only one file in a language was changes. examples: changes to FE only, still need to receive BE coverage; or you’re working in a monorepository, and only one module was changed, Codacy still expects coverage for the entire repository

**Comment by prcr** [comment]
> @prcr I'm not sure if we are also stressing that users must send coverage information for all files for every commit, regardless if only one file in a language was changes. examples: changes to FE only, still need to receive BE coverage; or you’re working in a monorepository, and only one module was changed, Codacy still expects coverage for the entire repository

It was already mentioned in the previous section about generating the coverage reports, but it's never too late to remind the users again. I pushed this change:

image

**Review by nicklem — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
