### PR TITLE
clean: Edit page titles to use sentence case consistently

### PR DESCRIPTION
**Pull request by prcr**
While navigating the docs I noticed that we could improve the consistency of page title capitalization. Almost all pages were already using sentence case, except for these:

- https://docs.codacy.com/repositories/repository-dashboard/
- https://docs.codacy.com/repositories/pull-requests/
- https://docs.codacy.com/repositories/security-monitor/
- https://docs.codacy.com/organizations/organization-overview/

This was because when I initially authored or reviewed the pages, I decided to capitalize all words in the concept names. For example:

- **Repository Dashboard**
- **Pull Requests** page
- **Security Monitor**
- **Organization Overview**

However, I'm thinking that if we simplify a bit and use sentence case also for the names of the concepts, the sidebar becomes both more elegant and simpler to read:

image

### :eyes: Live preview
https://clean-sidebar-sentence-case--docs-codacy.netlify.app

### CODE REVIEW

**Comment by prcr** [comment]
@claudiacarpinteiro @nicklem What do you think of this? Is it worthwhile making this change or perhaps not? :thinking:

**Comment by prcr** [comment]
> @prcr Not sure about the Security Monitor, but the remaining three titles are capitalized according to the UI copy, right?

Good point! Although the UI is also ambiguous, since the capitalization is not consistent there:

* On the sidebar, we have "Pull Requests" (title case) and "Code patterns" (sentence case)
* On the **Security** page, the title is "Security monitor" (sentence case)

Besides these inconsistencies, are we considering that the "Overview" in "Organization Overview" is part of the concept name, or it simply means "the overview of the organization" and we're just over complicating things? :sweat_smile:

**Comment by nicklem** [comment]
Nitpicks only tech writers can understand 😄 

It's a grey area. I lean towards capitalizing what may count as a "feature," so also a dashboard (Organization Overview, Pull requests page), especially since it's more readable when contextualized, as it lends the feel of a single concept to multiple words.

But I'm open to anything we decide to follow as a standard.

**Comment by prcr** [comment]
Taking your feedback into account, I decided that it's best to keep the existing version - the rationale that I followed originally when authoring or reviewing these pages is aligned with your arguments. :ok_hand:

**Pull request closed without merging**
