### PR TITLE
feature: Documentation for Plan and billing page DOCS-241

### PR DESCRIPTION
**Pull request by prcr**
Adds dedicated documentation for the **Plan and billing** page under the organization settings.

Addresses the [feedback from Joana](https://codacy.slack.com/archives/C011BCR2RN3/p1617972376011400) so that we can provide a documentation page for people interested in upgrading their plan without being focused on cancellation.

I also moved the details about the configuration **Accepting new people to Codacy** to this new page, simplifying the page about managing people.

Preview of the new page:

https://github.com/codacy/docs/blob/feature/plan-billing-DOCS-241/docs/organizations/changing-your-plan-and-billing.md

image

### CODE REVIEW

**Review by inesgomas — APPROVED** [review]

**Comment by ritagrilo** [comment]
Why do we say? 

> To change your Pro plan, please contact mailto:support@codacy.com.

As far as I'm aware, people can self-manage unless they are paying by wire transfer. 

We could add a more specific note about it or just have something generic, saying "if you need help with your account, please contact mailto:support@codacy.com."

**Comment by IGFCoimbra** [comment]
When users have their pricing plan linked to GitHub marketplace the setting to select which users can join without a request isn't available. Instead, afaik, all users will have to make the request. Should this be added to the documentation?

**Review by IGFCoimbra — APPROVED** [review]

**Comment by prcr** [comment]
> When users have their pricing plan linked to GitHub marketplace the setting to select which users can join without a request isn't available. Instead, afaik, all users will have to make the request. Should this be added to the documentation?

Good point @IGFCoimbra. I included a disclaimer for the organization plans managed through GitHub Marketplace, as it's important to clarify what happens in this scenario.

**Comment by prcr** [comment]
> Why do we say?
> 
> > To change your Pro plan, please contact mailto:[support@codacy.com](mailto:support@codacy.com).
> 
> As far as I'm aware, people can self-manage unless they are paying by wire transfer.
> 
> We could add a more specific note about it or just have something generic, saying "if you need help with your account, please contact mailto:[support@codacy.com](mailto:support@codacy.com)."

Thanks for pointing this out. I was incorrectly assuming that organizations on the Pro plan always needed manual intervention when customers wanted to change their details. I updated the instructions for this scenario accordingly and kept the email contact as a last resort for questions and any change that the Codacy UI may not support. :+1:

**Review by inesgomas — APPROVED** [review]

**Pull request merged**
