### PR TITLE
feature: Mention unavailable grade and badges after DB maintenance

### PR DESCRIPTION
**Pull request by prcr**
We noticed that the DB maintenance operation had another side effect which is the unavailable grade and badges for repositories that didn't have any commit within the "retention period".

On Customer Support we've been having a few tickets about this, so I suggest that we add this detail to make it more convenient to refer customers to the information on this page.

### CODE REVIEW

**Review by IGFCoimbra — COMMENTED** [review]
Instead of "any commits and pull requests that we don't re-analyze as part of the maintenance operation" I would prefer something similar to "All repos that haven't had an analysis since the maintenance operation".

I think that the full universe of people affected by this are open source users (as we have re-analyzed all the paid and trial repos) and this message as is can alienate them

**Comment by prcr** [comment]
> Instead of "any commits and pull requests that we don't re-analyze as part of the maintenance operation" I would prefer something similar to "All repos that haven't had an analysis since the maintenance operation".
> 
> I think that the full universe of people affected by this are open source users (as we have re-analyzed all the paid and trial repos) and this message as is can alienate them

The plan was to also analyze repositories on Open Source plans, but with a shorter "retention period" of 15 days. What I believe could be happening is that some repositories didn't have any commit within the 15 day period and because of that those repositories weren't re-analyzed and the grades/badges weren't refreshed.

@medleycodacy or @h314to, do you validate that the re-analysis for these repositories was completed successfully during the maintenance operation and that only part of these repositories are likely to have the grade/badge missing?

**Comment by codacychallenge** [comment]
All the repos outside of the re-analysis defined period will not have commits, prs, files and information in the dashboard been the badge one of the info missing ones.

more detailed information:
https://docs.google.com/document/d/1w6j5dp_0I0QH7BXMymrlVpBzp2SYnXbUS-Zns1IlQzs/edit

**Comment by medleycodacy** [comment]
All the repos outside of the re-analysis defined period will not have commits, prs, files and information in the dashboard been the badge one of the info missing ones.

more detailed information:
https://docs.google.com/document/d/1w6j5dp_0I0QH7BXMymrlVpBzp2SYnXbUS-Zns1IlQzs/edit

**Comment by h314to** [comment]
> > Instead of "any commits and pull requests that we don't re-analyze as part of the maintenance operation" I would prefer something similar to "All repos that haven't had an analysis since the maintenance operation".
> > I think that the full universe of people affected by this are open source users (as we have re-analyzed all the paid and trial repos) and this message as is can alienate them
> 
> The plan was to also analyze repositories on Open Source plans, but with a shorter "retention period" of 15 days. What I believe could be happening is that some repositories didn't have any commit within the 15 day period and because of that those repositories weren't re-analyzed and the grades/badges weren't refreshed.
> 
> @medleycodacy or @h314to, do you validate that the re-analysis for these repositories was completed successfully during the maintenance operation and that only part of these repositories are likely to have the grade/badge missing?

yes, the reanalysis was successfully performed for open source plans matching the agreed criteria (15 days retention)

**Review by madalenamelo — APPROVED** [review]

**Pull request merged**
