### PR TITLE
toolchain: Update list of tool UUIDs to ignore DOCS-613

### LINKED ISSUE #1939: Missing supported tools report
Checking if each tool is included in the documentation.

✅ Cppcheck is included (C, CPP)
✅ Clang-Tidy is included (C, CPP, Objective C)
✅ Deadcode is included (Go)
❌ JSHint (deprecated) ISN'T included (Javascript)
✅ Checkov is included (JSON, YAML, Terraform)
✅ Staticcheck is included (Go)
✅ Stylelint is included (CSS, LESS, SASS)
✅ Scalastyle is included (Scala)
✅ ShellCheck is included (Shell)
✅ Prospector is included (Python)
✅ SQLint is included (SQL, PLSQL)
✅ Ameba is included (Crystal)
✅ Trivy is included (Dart, TypeScript, Python, Javascript, Elixir, PHP, C, CSharp, Swift, CPP, JSON, Rust, Ruby, Terraform, Go, Java, Dockerfile, YAML)
✅ Pylint is included (Python)
✅ TSQLLint is included (SQL, TSQL)
❌ bundler-audit (deprecated) ISN'T included (Ruby)
✅ PHP Mess Detector is included (PHP)
✅ Jackson Linter is included (JSON)
✅ markdownlint is included (Markdown)
❌ TSLint (deprecated) ISN'T included (TypeScript)
✅ Codacy ScalaMeta Pro is included (Scala)
✅ Credo is included (Elixir)
✅ CoffeeLint is included (CoffeeScript)
✅ RuboCop is included (Ruby)
✅ Aligncheck is included (Go)
✅ Flawfinder is included (C, CPP)
✅ SonarC# is included (CSharp)
✅ Bandit is included (Python)
✅ PSScriptAnalyzer is included (Powershell)
✅ SwiftLint is included (Swift)
❌ CSSLint (deprecated) ISN'T included (CSS)
✅ PMD is included (PLSQL, XML, JSP, Velocity, Apex, Javascript, VisualForce, Java, SQL)
✅ SonarVB is included (VisualBasic)
✅ Unity Roslyn Analyzers is included (CSharp)
✅ Revive is included (Go)
✅ Brakeman is included (Ruby)
✅ detekt is included (Kotlin)
❌ Faux Pas (deprecated) ISN'T included (Objective C)
✅ dartanalyzer is included (Dart)
✅ Hadolint is included (Dockerfile)
✅ CodeNarc is included (Groovy)
✅ SpotBugs is included (Java, Scala)
❌ tailor (deprecated) ISN'T included (Swift)
✅ Gosec is included (Go)
✅ remark-lint is included (Markdown)
✅ Checkstyle is included (Java)
✅ PHP_CodeSniffer is included (PHP)
✅ ESLint is included (Javascript, TypeScript)
✅ Spectral is included (YAML, JSON)

Found 6 tools that aren't included in the documentation.

### LINKED ISSUE #1940: Missing security tools report
Checking if each tool that detects security issues is included in the documentation:

✅ Cppcheck (C, CPP) is included, supports 5 security code patterns
✅ Clang-Tidy (C, CPP, Objective C) is included, supports 28 security code patterns
✅ Checkov (JSON, YAML, Terraform) is included, supports 248 security code patterns
✅ ShellCheck (Shell) is included, supports 4 security code patterns
✅ Prospector (Python) is included, supports 2 security code patterns
✅ Trivy (Dart, TypeScript, Python, Javascript, Elixir, PHP, C, CSharp, Swift, CPP, JSON, Rust, Ruby, Terraform, Go, Java, Dockerfile, YAML) is included, supports 2 security code patterns
✅ Pylint (Python) is included, supports 2 security code patterns
✅ TSQLLint (SQL, TSQL) is included, supports 1 security code patterns
❌ bundler-audit (deprecated) (Ruby) ISN'T included, supports 2 security code patterns
✅ PHP Mess Detector (PHP) is included, supports 1 security code patterns
✅ Codacy ScalaMeta Pro (Scala) is included, supports 35 security code patterns
✅ Credo (Elixir) is included, supports 2 security code patterns
✅ RuboCop (Ruby) is included, supports 7 security code patterns
✅ Flawfinder (C, CPP) is included, supports 222 security code patterns
✅ SonarC# (CSharp) is included, supports 73 security code patterns
✅ Bandit (Python) is included, supports 78 security code patterns
✅ PSScriptAnalyzer (Powershell) is included, supports 6 security code patterns
✅ PMD (PLSQL, XML, JSP, Velocity, Apex, Javascript, VisualForce, Java, SQL) is included, supports 17 security code patterns
✅ SonarVB (VisualBasic) is included, supports 24 security code patterns
✅ Brakeman (Ruby) is included, supports 69 security code patterns
✅ Hadolint (Dockerfile) is included, supports 4 security code patterns
✅ CodeNarc (Groovy) is included, supports 10 security code patterns
✅ SpotBugs (Java, Scala) is included, supports 182 security code patterns
✅ Gosec (Go) is included, supports 34 security code patterns
✅ PHP_CodeSniffer (PHP) is included, supports 59 security code patterns
✅ ESLint (Javascript, TypeScript) is included, supports 44 security code patterns

Found 1 tools that aren't included in the documentation.

### PR DESCRIPTION
**Pull request by prcr**
The scheduled scripts that check the list of supported tools have been failing for a few weeks now, since there are a few tools that were deprecated and removed from the docs (see https://docs.codacy.com/release-notes/cloud/cloud-2023-10-25-csslint-jshint-fauxpas-tailor-tslint-deprecation/ and https://docs.codacy.com/release-notes/cloud/cloud-2023-10-13-bundler-audit-deprecation/.

This pull request updates the list of tool UUIDs that the scripts ignore, so that they no longer fail.

Fixes #1939.
Fixes #1940.

### CODE REVIEW

**Review by nicklem — APPROVED** [review]
Thanks @prcr! Much appreciated. This has been on the backburner for a while now; glad you took a look.

I was planning on adding one such variable and didn't even realize one was already available! 😄

**Comment by nicklem** [comment]
We're having some trouble with running the `mkdocs` status check. Closing and reopening this one.

**Comment by prcr** [comment]
> We're having some trouble with running the `mkdocs` status check. Closing and reopening this one.

You'll probably have to replicate the changes on your own pull request opened directly on the repository. Since the mkdocs workflow requires access to the secret `secrets.DEPLOYMENT_PERSONAL_ACCESS_TOKEN`, I don't think there's a way to make it run on pull requests opened from forked repositories. :thinking:

**Comment by nicklem** [comment]
Closing and duplicating these edits in https://github.com/codacy/docs/pull/1952; there's some issue with `mkdocs`.

**Pull request closed without merging**
