### PR TITLE
fix: Don't wrap on ToC overflow

### PR DESCRIPTION
**Pull request by mrfyda**
Fix from codacy/codacy-mkdocs-material#28

### CODE REVIEW

**Comment by mrfyda** [comment]
@prcr did I need to generate files on the theme for them to take effect?

**Comment by prcr** [comment]
> @prcr did I need to generate files on the theme for them to take effect?

Yes, following [these instructions](https://squidfunk.github.io/mkdocs-material/customization/#building-the-theme). :slightly_smiling_face: I think that in this pull request you're only updating the generated files from a previous small change that I had made but hadn't propagated to this repository.

**Comment by mrfyda** [comment]
> > @prcr did I need to generate files on the theme for them to take effect?
> 
> Yes, following [these instructions](https://squidfunk.github.io/mkdocs-material/customization/#building-the-theme). 🙂 I think that in this pull request you're only updating the generated files from a previous small change that I had made but hadn't propagated to this repository.

fixed!

**Review by prcr — APPROVED** [review]
:shipit: :rocket:

**Pull request merged**
