### PR TITLE
feat: Coding Standards read-only page IO-340

### PR DESCRIPTION
**Pull request by nicklem**
Updates to reflect the new capability, available to all users, to list existing coding standards.

### :eyes: Live preview
* https://feat-coding-standards-read-only-io--docs-codacy.netlify.app/organizations/roles-and-permissions-for-organizations/
* Various screenshots (see diffs)

### :construction: To do
-   [x] Copy
    - [x] Review
-  [x] Screenshots
    - [x] Review

### CODE REVIEW

**Review by prcr — APPROVED** [review]
Great work updating all the screenshots! :muscle: I hadn't remembered this maintenance cost yet.

I also agree with updating the "roles and permissions tables" to make things more explicit. :+1: 

:shipit: :rocket:

**Comment by andre-a-pires** [comment]
@nicklem @prcr cheers for involving me in the process

**Review by andre-a-pires — APPROVED** [review]
Looks fine to me

**Comment by nicklem** [comment]
Together with @prcr, we decided to revert the changes to the roles and permissions table.
We're already omitting several trivial permissions, and we can consider "listing coding standards" to be one of them.

**Pull request merged**
